In [1]:
import pandas as pd

df1 = pd.read_csv("data1.csv")
df2 = pd.read_csv("data2.csv")

df = pd.merge(df1,df2,how = 'inner',on='ID')  #ID기준으로 합치기
df.drop(['Date_x','Date_y','ID'], axis = 1, inplace = True)
df

,Gender,Age,Shift,Injury Location,Incident Type,Days Lost,Incident Cost
0,Male,25,Night,Trunk,Burn,0.0,"$5,000"
1,Female,18,Day,Abdomen,Cut,0.0,"$4,994"
2,Male,35,Day,Back,Lifting,5.0,"$4,969"
3,Female,50,Day,Legs,Lifting,2.5,4947
4,Male,25,Day,Abdomen,Lifting,3.0,"$4,940"
...,...,...,...,...,...,...,...
509,Female,31,Night,Back,Lifting,0.0,0
510,Male,31,Night,Back,Slip/trip,0.0,0
511,Male,22,Night,Abdomen,Crush & Pinch,0.0,0
512,Male,31,Night,Hands,Lifting,0.0,0
513,Male,60,Night,Hands,Cut,0.0,0

In [2]:
df.dropna(inplace = True)  #결측치 제거
df['Incident Cost'] = df['Incident Cost'].str.replace(pat =r'[^\w]', repl=r'', regex=True ) #특수문자 제거
df

,Gender,Age,Shift,Injury Location,Incident Type,Days Lost,Incident Cost
0,Male,25,Night,Trunk,Burn,0.0,5000
1,Female,18,Day,Abdomen,Cut,0.0,4994
2,Male,35,Day,Back,Lifting,5.0,4969
3,Female,50,Day,Legs,Lifting,2.5,4947
4,Male,25,Day,Abdomen,Lifting,3.0,4940
...,...,...,...,...,...,...,...
509,Female,31,Night,Back,Lifting,0.0,0
510,Male,31,Night,Back,Slip/trip,0.0,0
511,Male,22,Night,Abdomen,Crush & Pinch,0.0,0
512,Male,31,Night,Hands,Lifting,0.0,0
513,Male,60,Night,Hands,Cut,0.0,0

In [3]:
#https://rfriend.tistory.com/521
import numpy as np
# bins = [0,30,40,50]
# bins = [0,30,50]
bins = [0,20,30,40,50]

df['Age_grouping'] = np.digitize(df['Age'], bins)
df

,Gender,Age,Shift,Injury Location,Incident Type,Days Lost,Incident Cost,Age_grouping
0,Male,25,Night,Trunk,Burn,0.0,5000,2
1,Female,18,Day,Abdomen,Cut,0.0,4994,1
2,Male,35,Day,Back,Lifting,5.0,4969,3
3,Female,50,Day,Legs,Lifting,2.5,4947,5
4,Male,25,Day,Abdomen,Lifting,3.0,4940,2
...,...,...,...,...,...,...,...,...
509,Female,31,Night,Back,Lifting,0.0,0,3
510,Male,31,Night,Back,Slip/trip,0.0,0,3
511,Male,22,Night,Abdomen,Crush & Pinch,0.0,0,2
512,Male,31,Night,Hands,Lifting,0.0,0,3
513,Male,60,Night,Hands,Cut,0.0,0,5

In [4]:
df['Injury Location'].unique()

array(['Trunk', 'Abdomen', 'Back', 'Legs', 'Neck', 'Head', 'Multiple',
       'Eye', 'Arms', 'Hands', 'Feet'], dtype=object)

In [5]:
# map_Injury = {'Trunk' : 0, 'Abdomen' : 0, 'Back' : 0, 'Legs' : 1, 'Neck':2, 'Head' : 2, 'Multiple':3,
#        'Eye':4, 'Arms': 5, 'Hands' : 5, 'Feet' : 1}
# df['target'] = df['Injury Location'].map(map_Injury)
# df

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['scaled_DaysLost','scaled_IncidentCost']] = scaler.fit_transform(df[['Days Lost','Incident Cost']])

df

,Gender,Age,Shift,Injury Location,Incident Type,Days Lost,Incident Cost,Age_grouping,scaled_DaysLost,scaled_IncidentCost
0,Male,25,Night,Trunk,Burn,0.0,5000,2,0.0,1.0000
1,Female,18,Day,Abdomen,Cut,0.0,4994,1,0.0,0.9988
2,Male,35,Day,Back,Lifting,5.0,4969,3,1.0,0.9938
3,Female,50,Day,Legs,Lifting,2.5,4947,5,0.5,0.9894
4,Male,25,Day,Abdomen,Lifting,3.0,4940,2,0.6,0.9880
...,...,...,...,...,...,...,...,...,...,...
509,Female,31,Night,Back,Lifting,0.0,0,3,0.0,0.0000
510,Male,31,Night,Back,Slip/trip,0.0,0,3,0.0,0.0000
511,Male,22,Night,Abdomen,Crush & Pinch,0.0,0,2,0.0,0.0000
512,Male,31,Night,Hands,Lifting,0.0,0,3,0.0,0.0000
513,Male,60,Night,Hands,Cut,0.0,0,5,0.0,0.0000

In [7]:
# df.drop(['Gender','Age','Injury Location','Days Lost','Incident Cost'], axis = 1, inplace = True)
df.drop(['Gender','Age','Days Lost','Incident Cost'], axis = 1, inplace = True)
df.sort_values('Age_grouping', ascending=True)

df

,Shift,Injury Location,Incident Type,Age_grouping,scaled_DaysLost,scaled_IncidentCost
0,Night,Trunk,Burn,2,0.0,1.0000
1,Day,Abdomen,Cut,1,0.0,0.9988
2,Day,Back,Lifting,3,1.0,0.9938
3,Day,Legs,Lifting,5,0.5,0.9894
4,Day,Abdomen,Lifting,2,0.6,0.9880
...,...,...,...,...,...,...
509,Night,Back,Lifting,3,0.0,0.0000
510,Night,Back,Slip/trip,3,0.0,0.0000
511,Night,Abdomen,Crush & Pinch,2,0.0,0.0000
512,Night,Hands,Lifting,3,0.0,0.0000
513,Night,Hands,Cut,5,0.0,0.0000

In [8]:
map_Injury = {'Trunk' : 0, 'Abdomen' : 1, 'Back' : 2, 'Legs' : 3, 'Neck':4, 'Head' : 5, 'Multiple':6,
       'Eye':7, 'Arms': 8, 'Hands' : 9, 'Feet' : 10}
df['target'] = df['Injury Location'].map(map_Injury)
df

,Shift,Injury Location,Incident Type,Age_grouping,scaled_DaysLost,scaled_IncidentCost,target
0,Night,Trunk,Burn,2,0.0,1.0000,0
1,Day,Abdomen,Cut,1,0.0,0.9988,1
2,Day,Back,Lifting,3,1.0,0.9938,2
3,Day,Legs,Lifting,5,0.5,0.9894,3
4,Day,Abdomen,Lifting,2,0.6,0.9880,1
...,...,...,...,...,...,...,...
509,Night,Back,Lifting,3,0.0,0.0000,2
510,Night,Back,Slip/trip,3,0.0,0.0000,2
511,Night,Abdomen,Crush & Pinch,2,0.0,0.0000,1
512,Night,Hands,Lifting,3,0.0,0.0000,9
513,Night,Hands,Cut,5,0.0,0.0000,9

In [9]:
train = df[df['Age_grouping'] <5]
test = df[df['Age_grouping'] == 5]
# train['Age_grouping'] = train['Age_grouping'].astype(object)
# test['Age_grouping'] = test['Age_grouping'].astype(object)
train.drop('Age_grouping', axis = 1, inplace = True)
test.drop('Age_grouping', axis = 1, inplace = True)

C:\Users\jaewo\AppData\Local\Temp\ipykernel_4588\2781084914.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop('Age_grouping', axis = 1, inplace = True)
C:\Users\jaewo\AppData\Local\Temp\ipykernel_4588\2781084914.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop('Age_grouping', axis = 1, inplace = True)

In [10]:
train = pd.get_dummies(train, dummy_na = False)
train

,scaled_DaysLost,scaled_IncidentCost,target,Shift_Day,Shift_Night,Injury Location_Abdomen,Injury Location_Arms,Injury Location_Back,Injury Location_Eye,Injury Location_Feet,...,Injury Location_Trunk,Incident Type_Burn,Incident Type_Crush & Pinch,Incident Type_Cut,Incident Type_Equipment,Incident Type_Fall,Incident Type_Falling object,Incident Type_Lifting,Incident Type_Slip/trip,Incident Type_Vehicle
0,0.0,1.0000,0,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
1,0.0,0.9988,1,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,1.0,0.9938,2,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0.6,0.9880,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,0.0,0.9866,4,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,0.0,0.0000,5,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
509,0.0,0.0000,2,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
510,0.0,0.0000,2,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
511,0.0,0.0000,1,0,1,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
512,0.0,0.0000,9,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [11]:
test= pd.get_dummies(test, dummy_na = False)
test

,scaled_DaysLost,scaled_IncidentCost,target,Shift_Day,Shift_Night,Injury Location_Abdomen,Injury Location_Arms,Injury Location_Back,Injury Location_Eye,Injury Location_Feet,...,Injury Location_Trunk,Incident Type_Burn,Incident Type_Crush & Pinch,Incident Type_Cut,Incident Type_Equipment,Incident Type_Fall,Incident Type_Falling object,Incident Type_Lifting,Incident Type_Slip/trip,Incident Type_Vehicle
3,0.5,0.9894,3,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,0.4,0.9816,2,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
9,0.7,0.9744,4,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,0.0,0.9668,7,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
18,0.8,0.9542,3,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,0.0,0.0000,8,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
504,0.0,0.0000,7,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
507,0.0,0.0000,9,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
508,0.0,0.0000,10,1,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
513,0.0,0.0000,9,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [12]:
# df = pd.get_dummies(df, dummy_na=False)
# df

In [13]:
# from sklearn.model_selection import train_test_split
# x_train, x_test, y_train, y_test = train_test_split(df.drop('target', 1), df['target'], test_size=0.2, shuffle=True)

In [14]:
# train = df[df['Age_grouping'] <5]
# test = df[df['Age_grouping'] == 5]
# # train['Age_grouping'] = train['Age_grouping'].astype(object)
# # test['Age_grouping'] = test['Age_grouping'].astype(object)
# train.drop('Age_grouping', axis = 1, inplace = True)
# test.drop('Age_grouping', axis = 1, inplace = True)

In [15]:
# train = pd.get_dummies(train, dummy_na = False)
# train

In [16]:
# test= pd.get_dummies(test, dummy_na = False)
# test

In [17]:
x_train = train.drop('target',1)
y_train = train['target']

x_test = test.drop('target',1)
y_test = test['target']

len(x_train), len(y_train)

C:\Users\jaewo\AppData\Local\Temp\ipykernel_4588\275247721.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x_train = train.drop('target',1)
C:\Users\jaewo\AppData\Local\Temp\ipykernel_4588\275247721.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x_test = test.drop('target',1)

(362, 362)

In [18]:
y_train

0      0
1      1
2      2
4      1
5      4
      ..
506    5
509    2
510    2
511    1
512    9
Name: target, Length: 362, dtype: int64

In [20]:
y_test

3       3
6       2
9       4
13      7
18      3
       ..
503     8
504     7
507     9
508    10
513     9
Name: target, Length: 110, dtype: int64

In [22]:
x_train

,scaled_DaysLost,scaled_IncidentCost,Shift_Day,Shift_Night,Injury Location_Abdomen,Injury Location_Arms,Injury Location_Back,Injury Location_Eye,Injury Location_Feet,Injury Location_Hands,...,Injury Location_Trunk,Incident Type_Burn,Incident Type_Crush & Pinch,Incident Type_Cut,Incident Type_Equipment,Incident Type_Fall,Incident Type_Falling object,Incident Type_Lifting,Incident Type_Slip/trip,Incident Type_Vehicle
0,0.0,1.0000,0,1,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
1,0.0,0.9988,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,1.0,0.9938,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0.6,0.9880,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,0.0,0.9866,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,0.0,0.0000,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
509,0.0,0.0000,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
510,0.0,0.0000,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
511,0.0,0.0000,0,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
512,0.0,0.0000,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [21]:
x_test

,scaled_DaysLost,scaled_IncidentCost,Shift_Day,Shift_Night,Injury Location_Abdomen,Injury Location_Arms,Injury Location_Back,Injury Location_Eye,Injury Location_Feet,Injury Location_Hands,...,Injury Location_Trunk,Incident Type_Burn,Incident Type_Crush & Pinch,Incident Type_Cut,Incident Type_Equipment,Incident Type_Fall,Incident Type_Falling object,Incident Type_Lifting,Incident Type_Slip/trip,Incident Type_Vehicle
3,0.5,0.9894,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,0.4,0.9816,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9,0.7,0.9744,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,0.0,0.9668,1,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
18,0.8,0.9542,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,0.0,0.0000,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
504,0.0,0.0000,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
507,0.0,0.0000,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
508,0.0,0.0000,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
513,0.0,0.0000,0,1,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0

In [19]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=0)
dt.fit(x_train, y_train)
dt_pred = dt.predict(x_test)
(dt_pred == y_test).mean()

1.0